<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>ElleMapper</PackageId>
		<Version>1.0.3</Version>
		<Author>Lin Thit Htoo</Author>
		<Product>ElleMapper</Product>
		<IsPackable>true</IsPackable>
		<RepositoryUrl>https://github.com/Linn-Thit-Htoo/ElleMapper.git</RepositoryUrl>
		<Description>Core ORM package</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0-preview2.25289.6" />
	</ItemGroup>

</Project>
