<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>ElleMapper.MySql</PackageId>
		<Version>1.0.3</Version>
		<Author>Lin Thit Htoo</Author>
		<PackageIcon>Ellemapper.jpg</PackageIcon>
		<Product>ElleMapper.MySql</Product>
		<IsPackable>true</IsPackable>
		<RepositoryUrl>https://github.com/Linn-Thit-Htoo/ElleMapper.git</RepositoryUrl>
		<Description>MySql database provider for ElleMapper ORM</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ElleMapper" Version="1.0.9" />
		<PackageReference Include="MySqlConnector" Version="2.5.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Ellemapper.jpg" Pack="true" PackagePath="/" />
	</ItemGroup>

</Project>
